modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "effectual"
version = "${version}"
displayName = "Effectual"
authors = "iMeeTake"
description = '''
Atmospheric effects and decorative particles.
'''
logoFile = "icon.png"

[[dependencies.effectual]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.118,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "tlib"
mandatory = true
versionRange = "[1.5.0-1.20.1,)"
ordering = "AFTER"
side = "CLIENT"
