modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "effectual"
version = "${version}"
displayName = "Effectual"
authors = "iMeeTake"
description = '''
Atmospheric effects and decorative particles.
'''
logoFile = "icon.png"

[[dependencies.effectual]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "tlib"
type = "required"
versionRange = "[1.5.0-1.21.1,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "effectual.mixins.json"
