modLoader = "javafml"
loaderVersion = "[10,)"
license = "MIT"

[[mods]]
modId = "effectual"
version = "${version}"
displayName = "Effectual"
authors = "iMeeTake"
description = '''
Atmospheric effects and decorative particles.
'''
logoFile = "icon.png"

[[dependencies.effectual]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.effectual]]
modId = "architectury"
type = "required"
versionRange = "[20.0.5,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "cloth_config"
type = "required"
versionRange = "[26.1.154,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.effectual]]
modId = "tlib"
type = "required"
versionRange = "[1.5.0-26.1.2,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "effectual.mixins.json"
